data_sources:
  mysql:
    host:
    port:
    database:
    user:
    password:

  postgresql:
    host:
    port:
    database:
    user:
    password:

  bigquery:
    project_id:
    dataset:
    credentials_path:

processing:
  batch_size: 1000
  max_workers: 4
  timeout_seconds: 300



